import VerifyPasswordCodeForm from "@/app/auth/VerifyPasswordCodeForm/VerifyPasswordCodeForm";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Verify Password",
  description: "Generated by create next app",
};
export default function VerifyPasswordCode() {
  return (
    <>
      <VerifyPasswordCodeForm />
    </>
  );
}
