import ResetPasswordForm from "@/app/auth/ResetPasswordForm/ResetPasswordForm";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Reset Password",
  description: "Generated by create next app",
};
export default function ResetPassword() {
  return (
    <>
      <ResetPasswordForm />
    </>
  );
}
