import RegisterForm from "@/app/auth/RegisterForm/RegisterForm";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Register",
  description: "Generated by create next app",
};
export default function Register() {
  return (
    <>
      <RegisterForm />
    </>
  );
}
