import AllOrdersCard from "@/app/_components/allOrdersCard/AllOrdersCard";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "All Orders",
  description: "Generated by create next app",
};

export default function MyOrders() {
  return (
    <>
      <AllOrdersCard />
    </>
  );
}
