import LoginForm from "@/app/auth/LoginForm/LoginForm";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Login",
  description: "Generated by create next app",
};
export default function Login() {
  return (
    <>
      <LoginForm />
    </>
  );
}
