import CategoryCard from "@/app/_components/categoryCard/CategoryCard";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Categories",
  description: "Generated by create next app",
};
export default function Categories() {
  return (
    <>
      <CategoryCard />
    </>
  );
}
