import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/_components/navbar/Navbar";
import { Toaster } from "react-hot-toast";
import MyProvider from "@/MyProvider/MyProvider";
import { ThemeProvider } from "next-themes";
import CartContextProvider from "@/context/CartContext";
import Providers from "@/MyProvider/TanstackProvider";
import Footer from "@/app/_components/footer/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "FreshCart",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} dark:bg-zinc-900  antialiased`}
      >
        <ThemeProvider attribute={"class"} defaultTheme="light">
          <Providers>
            <MyProvider>
              <CartContextProvider>
                <Toaster />
                <Navbar />
                <div className="min-h-screen">{children}</div>
                <Footer />
              </CartContextProvider>
            </MyProvider>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  );
}
