import CheckOutCard from "@/app/_components/checkoutCard/CheckOutCard";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Checkout",
  description: "Generated by create next app",
};
export default function CheckOut() {
  return (
    <>
      <CheckOutCard />
    </>
  );
}
