import WishListCard from "@/app/_components/wishListCard/WishListCard";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Wishlist",
  description: "Generated by create next app",
};
export default function page() {
  return <WishListCard />;
}
