import CartCard from "@/app/_components/CartCard/CartCard";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Cart",
  description: "Generated by create next app",
};
function Cart() {
  return (
    <>
      <CartCard />
    </>
  );
}

export default Cart;
