import ForgetPasswordForm from "@/app/auth/ForgotPassword/ForgotPasswordForm";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Forgot Password",
  description: "Generated by create next app",
};

export default function ForgotPassword() {
  return (
    <>
      <ForgetPasswordForm />
    </>
  );
}
