import BrandCard from "@/app/_components/brandCard/BrandCard";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Brands",
  description: "Generated by create next app",
};

export default function Brands() {
  return (
    <>
      <BrandCard />
    </>
  );
}
