import MainProducts from "@/app/_components/mainProducts/MainProducts";
import { Metadata } from "next";
export const metadata: Metadata = {
  title: "Products",
  description: "Generated by create next app",
};
function Products() {
  return (
    <>
      <section>
        <div className="container p-5">
          <div className="grid gap-4 grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5">
            <MainProducts />
          </div>
        </div>
      </section>
    </>
  );
}

export default Products;
